### ISSUE TITLE
nesting of 5 is too deep

### ISSUE THREAD

**Issue by VitaliyAdamkov** [erickj/bkblz#1]
Hi & thank you for the gem.

Today I've tried to list my buckets with its Bkblz::V1::ListBucketsRequest.new method & 've got "nesting of 5 is too deep" error from .rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bkblz-0.1.7/lib/bkblz/v1/response.rb:74:in `parse'.

If I change :max_nesting (in source file mentioned below) value to 5 or greater, it works OK.

Can you make it possible to set this value manually?

**Comment by erickj** [comment]
I'll try to take a look as soon as I can. It might take me a few days to get to it though.

**Comment by erickj** [comment]
changed the new hardcoded value to 10, i don't want to provide a config for it yet if a simpler fix will work

**Comment by VitaliyAdamkov** [comment]
thanks a lot :)
